import quit
import echo
import help
import floodcontrol
import ctcpversion
import nickscore
import linktitle
import quotes
import reply
import spew
import greetings
import colors
import feeds
import autoupdate
import poll
import statistics
import roulette
import loadaverage
import interjection
import admins
import ignore
import imagesearch
import channels
import weather
import kana
